[package]
name = "space"
version = "0.1.0"
authors = ["Evin Owen <github@evinowen.net>","Greg Lamb <email@greglamb.me>"]
edition = "2018"

[dependencies]
warp = "0.2.5"
tokio = { version = "0.2", features = ["macros"] }
